/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface L1SLOADmockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decodeInput"
      | "mockedSlots"
      | "readMockedSlot"
      | "setMockedSlot"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "decodeInput",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mockedSlots",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "readMockedSlot",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMockedSlot",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "decodeInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockedSlots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readMockedSlot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMockedSlot",
    data: BytesLike
  ): Result;
}

export interface L1SLOADmock extends BaseContract {
  connect(runner?: ContractRunner | null): L1SLOADmock;
  waitForDeployment(): Promise<this>;

  interface: L1SLOADmockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decodeInput: TypedContractMethod<
    [data: BytesLike],
    [[string, bigint]],
    "view"
  >;

  mockedSlots: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  readMockedSlot: TypedContractMethod<
    [_l1ContactAddr: AddressLike, _slot: BigNumberish],
    [string],
    "view"
  >;

  setMockedSlot: TypedContractMethod<
    [l1ContactAddr: AddressLike, slot: BigNumberish, value: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decodeInput"
  ): TypedContractMethod<[data: BytesLike], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "mockedSlots"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "readMockedSlot"
  ): TypedContractMethod<
    [_l1ContactAddr: AddressLike, _slot: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMockedSlot"
  ): TypedContractMethod<
    [l1ContactAddr: AddressLike, slot: BigNumberish, value: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
