/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IL1SLOADmock,
  IL1SLOADmockInterface,
} from "../../../contracts/ToadnadoL2.sol/IL1SLOADmock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "fallback",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "hii",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IL1SLOADmock__factory {
  static readonly abi = _abi;
  static createInterface(): IL1SLOADmockInterface {
    return new Interface(_abi) as IL1SLOADmockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IL1SLOADmock {
    return new Contract(address, _abi, runner) as unknown as IL1SLOADmock;
  }
}
