/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IL2SLOADmock,
  IL2SLOADmockInterface,
} from "../../../contracts/ToadnadoL2.sol/IL2SLOADmock";

const _abi = [
  {
    inputs: [],
    name: "hii",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IL2SLOADmock__factory {
  static readonly abi = _abi;
  static createInterface(): IL2SLOADmockInterface {
    return new Interface(_abi) as IL2SLOADmockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IL2SLOADmock {
    return new Contract(address, _abi, runner) as unknown as IL2SLOADmock;
  }
}
