/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  L2SLOADmock,
  L2SLOADmockInterface,
} from "../../../contracts/ToadnadoL2.sol/L2SLOADmock";

const _abi = [
  {
    inputs: [],
    name: "hii",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class L2SLOADmock__factory {
  static readonly abi = _abi;
  static createInterface(): L2SLOADmockInterface {
    return new Interface(_abi) as L2SLOADmockInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): L2SLOADmock {
    return new Contract(address, _abi, runner) as unknown as L2SLOADmock;
  }
}
