/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  2227728: {
    ToadnadoL2: {
      address: "0x403F9ADd4272c24cf27DC3A5454aEE95B1DD9904",
      abi: [
        {
          inputs: [],
          name: "ROOT_HISTORY_SIZE",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentRootIndex",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "l1_contract",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "key",
              type: "uint256",
            },
          ],
          name: "getL1Root",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_root",
              type: "bytes32",
            },
          ],
          name: "isKnownL1Root",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_root",
              type: "bytes32",
            },
          ],
          name: "isKnownRoot",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "l1_contract",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "slot",
              type: "uint256",
            },
          ],
          name: "readSingleSlot",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  11155111: {
    ToadnadoL1: {
      address: "0x40F5D0001859b6D483282295F58616121ABA44BF",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_verifier",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "nullifiers",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "roots",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "_commitmentsTree",
              type: "bytes32[]",
            },
            {
              internalType: "bytes32",
              name: "_root",
              type: "bytes32",
            },
          ],
          name: "setCommitmentsTree",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "verifier",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "_commitmentsTree",
              type: "bytes32[]",
            },
            {
              internalType: "bytes32",
              name: "_root",
              type: "bytes32",
            },
          ],
          name: "setCommitmentsTree",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "_recipient",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "_nullifier",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "chainId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "snarkProof",
              type: "bytes",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "i",
              type: "uint256",
            },
          ],
          name: "zeros",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {
        FIELD_SIZE: "contracts/Toadnado.sol",
        ROOT_HISTORY_SIZE: "contracts/Toadnado.sol",
        ZERO_VALUE: "contracts/Toadnado.sol",
        commitmentLeafs: "contracts/Toadnado.sol",
        commitments: "contracts/Toadnado.sol",
        commitmentsTree: "contracts/Toadnado.sol",
        commitmentsTreeRoots: "contracts/Toadnado.sol",
        currentRootIndex: "contracts/Toadnado.sol",
        denomination: "contracts/Toadnado.sol",
        deposit: "contracts/Toadnado.sol",
        filledSubtrees: "contracts/Toadnado.sol",
        getLastRoot: "contracts/Toadnado.sol",
        hashLeftRight: "contracts/Toadnado.sol",
        isKnownRoot: "contracts/Toadnado.sol",
        levels: "contracts/Toadnado.sol",
        nextIndex: "contracts/Toadnado.sol",
        nullifiers: "contracts/Toadnado.sol",
        roots: "contracts/Toadnado.sol",
        setCommitmentsTree: "contracts/Toadnado.sol",
        verifier: "contracts/Toadnado.sol",
        withdraw: "contracts/Toadnado.sol",
        zeros: "contracts/Toadnado.sol",
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
